/* import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "../components/bottomnav/bottomnav"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <BottomNav />
      </body>
    </html>
  );
}*/

import type { Metadata, Viewport } from "next"; // Viewport 타입 추가
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientlayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 1. 뷰포트 설정 (viewport-fit=cover 포함)은 별도의 viewport 객체로 분리하는 것이 권장
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover", //  iOS 풀스크린 처리
  themeColor: "#ffffff", // 필요시 배경색에 맞춰 설정 (선택사항)
};

// 2. 메타데이터 설정
export const metadata: Metadata = {
  title: "Safe Food",
  description: "캡스톤 프로젝트 배송 상태 모니터링 시스템",
  manifest: "/manifest.json",
  // iOS 설정은 여기서 한 번만 정의하면 Next.js가 자동으로 <meta> 태그를 생성
  appleWebApp: {
    capable: true,
    title: "Safe Food",
    statusBarStyle: "black-translucent",
    startupImage: [], // 필요하면 스플래시 이미지 설정 가능
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head> 태그는 삭제. Next.js가 위 설정을 바탕으로 자동 생성. */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}